model:
  pe_file_name: maglap_5q_naive
  pe_type: maglap
  q: 0.1
  q_dim: 5
  pe_strategy: variant
  mag_pe_dim_input: 10
  mag_pe_dim_output: 10
  se_pe_dim_input: 0
  se_pe_dim_output: 0
  
  eigval_encoder:
    in: 1
    hidden: 32
    out: 8
    num_layer: 3

  pe_embedder:
    name: naive