model:
  pe_file_name: maglap_1q_gnn
  pe_type: maglap
  q: 0.01
  q_dim: 1
  pe_strategy: variant
  mag_pe_dim_input: 10
  mag_pe_dim_output: 10
  se_pe_dim_input: 0
  se_pe_dim_output: 0
  
  eigval_encoder:
    in: 1
    hidden: 32
    out: 8
    num_layer: 3

  pe_embedder:
    name: regular
    local_model: gnn
    sign_inv: 1
